server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.131:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-timeout: 30000 # 连接超时时间，单位毫秒
      minimum-idle: 5           # 最小空闲连接数
      maximum-pool-size: 20     # 最大连接池大小
      idle-timeout: 600000      # 空闲连接超时时间，单位毫秒
      max-lifetime: 1800000     # 连接最大生命周期，单位毫秒
      pool-name: HikariPool     # 连接池名称
      connection-test-query: select 1
  jackson:
    time-zone: GMT+8

# 日志配置
logging:
  config: classpath:log4j2.xml

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.demo01.mapper
  configuration:
    map-underscore-to-camel-case: true

# 自定义配置
app:
  name: demo01
  version: 1.0.0
  description: Spring Boot Demo Application